[2024-07-09T14:23:35.764+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pesquisa_industrial_anual_empresas.workspace manual__2024-07-09T14:23:34.841545+00:00 [queued]>
[2024-07-09T14:23:35.770+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pesquisa_industrial_anual_empresas.workspace manual__2024-07-09T14:23:34.841545+00:00 [queued]>
[2024-07-09T14:23:35.770+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-09T14:23:35.782+0000] {taskinstance.py:2217} INFO - Executing <Task(PapermillOperator): workspace> on 2024-07-09 14:23:34.841545+00:00
[2024-07-09T14:23:35.786+0000] {standard_task_runner.py:60} INFO - Started process 3842 to run task
[2024-07-09T14:23:35.788+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'pesquisa_industrial_anual_empresas', 'workspace', 'manual__2024-07-09T14:23:34.841545+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/pesquisa_industrial_anual_empresas/dags.py', '--cfg-path', '/tmp/tmpi6sdtqb8']
[2024-07-09T14:23:35.790+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask workspace
[2024-07-09T14:23:35.833+0000] {task_command.py:423} INFO - Running <TaskInstance: pesquisa_industrial_anual_empresas.workspace manual__2024-07-09T14:23:34.841545+00:00 [running]> on host 8596e3cff970
[2024-07-09T14:23:35.919+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='observatorio@sistemafiea.com.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pesquisa_industrial_anual_empresas' AIRFLOW_CTX_TASK_ID='workspace' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T14:23:34.841545+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T14:23:34.841545+00:00'
[2024-07-09T14:23:35.920+0000] {execute.py:83} INFO - Input Notebook:  /opt/***/dags/pesquisa_industrial_anual_empresas/notebooks/workspace.ipynb
[2024-07-09T14:23:35.920+0000] {execute.py:84} INFO - Output Notebook: /opt/***/dags/resultado/pesquisa_industrial_anual_empresas_workspace_2024-07-09.ipynb
[2024-07-09T14:23:37.218+0000] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2024-07-09T14:23:44.590+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/papermill/operators/papermill.py", line 118, in execute
    pm.execute_notebook(
  File "/home/airflow/.local/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/airflow/.local/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 df.write.mode("overwrite").show()

AttributeError: 'DataFrameWriter' object has no attribute 'show'

[2024-07-09T14:23:44.612+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pesquisa_industrial_anual_empresas, task_id=workspace, execution_date=20240709T142334, start_date=20240709T142335, end_date=20240709T142344
[2024-07-09T14:23:44.625+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task workspace (
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 df.write.mode("overwrite").show()

AttributeError: 'DataFrameWriter' object has no attribute 'show'
; 3842)
[2024-07-09T14:23:44.677+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-09T14:23:44.692+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
